### ISSUE TITLE
moloch not starting after reboot

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#15] opened 2018-07-10 14:54 UTC
Moloch is probably not starting because elastic is started later than moloch.
Manual starting works after elastic is running.

```
Jul 10 17:33:49 detector systemd[1]: Started molochviewer.service.
Jul 10 17:33:49 detector moloch-capture[1924]: Jul 10 17:33:49 main.c:610 main(): THREAD 0x7f71ad0b0780
Jul 10 17:33:49 detector moloch-capture[1924]: Jul 10 17:33:49 main.c:169 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - detector
Jul 10 17:33:49 detector moloch-capture[1924]: Jul 10 17:33:49 http.c:209 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jul 10 17:33:49 detector moloch-capture[1924]: Jul 10 17:33:49 db.c:1735 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Unit entered failed state.
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Failed with result 'exit-code'.
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:49 detector moloch-capture[2543]: Jul 10 17:33:49 main.c:610 main(): THREAD 0x7f7c2b297780
Jul 10 17:33:49 detector moloch-capture[2543]: Jul 10 17:33:49 main.c:169 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - detector
Jul 10 17:33:49 detector moloch-capture[2543]: Jul 10 17:33:49 http.c:209 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jul 10 17:33:49 detector moloch-capture[2543]: Jul 10 17:33:49 db.c:1735 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Unit entered failed state.
Jul 10 17:33:49 detector systemd[1]: molochcapture.service: Failed with result 'exit-code'.
Jul 10 17:33:50 detector systemd[1]: molochcapture.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:50 detector moloch-capture[2849]: Jul 10 17:33:50 main.c:610 main(): THREAD 0x7fe573879780
Jul 10 17:33:50 detector moloch-capture[2849]: Jul 10 17:33:50 main.c:169 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - detector
Jul 10 17:33:50 detector moloch-capture[2849]: Jul 10 17:33:50 http.c:209 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jul 10 17:33:50 detector moloch-capture[2849]: Jul 10 17:33:50 db.c:1735 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jul 10 17:33:50 detector systemd[1]: molochcapture.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:50 detector systemd[1]: molochcapture.service: Unit entered failed state.
Jul 10 17:33:50 detector systemd[1]: molochcapture.service: Failed with result 'exit-code'.
Jul 10 17:33:51 detector systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:51 detector systemd[1]: molochviewer.service: Unit entered failed state.
Jul 10 17:33:51 detector systemd[1]: molochviewer.service: Failed with result 'exit-code'.
Jul 10 17:33:51 detector systemd[1]: molochcapture.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:51 detector moloch-capture[2947]: Jul 10 17:33:51 main.c:610 main(): THREAD 0x7f602dc8b780
Jul 10 17:33:51 detector moloch-capture[2947]: Jul 10 17:33:51 main.c:169 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - detector
Jul 10 17:33:51 detector systemd[1]: molochviewer.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:51 detector systemd[1]: Stopped molochviewer.service.
Jul 10 17:33:51 detector systemd[1]: Started molochviewer.service.
Jul 10 17:33:51 detector moloch-capture[2947]: Jul 10 17:33:51 http.c:209 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jul 10 17:33:51 detector moloch-capture[2947]: Jul 10 17:33:51 db.c:1735 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jul 10 17:33:51 detector systemd[1]: molochcapture.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:51 detector systemd[1]: molochcapture.service: Unit entered failed state.
Jul 10 17:33:51 detector systemd[1]: molochcapture.service: Failed with result 'exit-code'.
Jul 10 17:33:51 detector systemd[1]: molochcapture.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:51 detector moloch-capture[2971]: Jul 10 17:33:51 main.c:610 main(): THREAD 0x7fb5f1e19780
Jul 10 17:33:51 detector moloch-capture[2971]: Jul 10 17:33:51 main.c:169 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps - detector
Jul 10 17:33:51 detector moloch-capture[2971]: Jul 10 17:33:51 http.c:209 moloch_http_send_sync(): libcurl failure http://localhost:9200/dstats/version/version/_source error 'Couldn't connect to server'
Jul 10 17:33:51 detector moloch-capture[2971]: Jul 10 17:33:51 db.c:1735 moloch_db_check(): ERROR - Couldn't load version information, database might be down or out of date.  Run "db/db.pl host:port upgrade"
Jul 10 17:33:52 detector systemd[1]: molochcapture.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:52 detector systemd[1]: molochcapture.service: Unit entered failed state.
Jul 10 17:33:52 detector systemd[1]: molochcapture.service: Failed with result 'exit-code'.
Jul 10 17:33:52 detector systemd[1]: molochcapture.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:52 detector systemd[1]: molochcapture.service: Start request repeated too quickly.
Jul 10 17:33:52 detector systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:52 detector systemd[1]: molochviewer.service: Unit entered failed state.
Jul 10 17:33:52 detector systemd[1]: molochviewer.service: Failed with result 'exit-code'.
Jul 10 17:33:52 detector systemd[1]: molochviewer.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:52 detector systemd[1]: Stopped molochviewer.service.
Jul 10 17:33:52 detector systemd[1]: Started molochviewer.service.
Jul 10 17:33:53 detector systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:53 detector systemd[1]: molochviewer.service: Unit entered failed state.
Jul 10 17:33:53 detector systemd[1]: molochviewer.service: Failed with result 'exit-code'.
Jul 10 17:33:54 detector systemd[1]: molochviewer.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:54 detector systemd[1]: Stopped molochviewer.service.
Jul 10 17:33:54 detector systemd[1]: Started molochviewer.service.
Jul 10 17:33:55 detector systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:55 detector systemd[1]: molochviewer.service: Unit entered failed state.
Jul 10 17:33:55 detector systemd[1]: molochviewer.service: Failed with result 'exit-code'.
Jul 10 17:33:55 detector systemd[1]: molochviewer.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:55 detector systemd[1]: Stopped molochviewer.service.
Jul 10 17:33:55 detector systemd[1]: Started molochviewer.service.
Jul 10 17:33:56 detector systemd[1]: molochviewer.service: Main process exited, code=exited, status=1/FAILURE
Jul 10 17:33:56 detector systemd[1]: molochviewer.service: Unit entered failed state.
Jul 10 17:33:56 detector systemd[1]: molochviewer.service: Failed with result 'exit-code'.
Jul 10 17:33:56 detector systemd[1]: molochviewer.service: Service hold-off time over, scheduling restart.
Jul 10 17:33:56 detector systemd[1]: Stopped molochviewer.service.
Jul 10 17:33:56 detector systemd[1]: molochviewer.service: Start request repeated too quickly.
Jul 10 17:33:56 detector systemd[1]: Failed to start molochviewer.service.
```

**Comment by roheline** [comment] 2018-07-10 14:56
s4a component versions
- server 0.1.62
- client 0.1.64
- main 0.1.68

**Comment by voldemarpanso** [comment] 2018-07-11 10:46
Looking at configuration it seems that it was falsely assumed that the issue is elasticsearch slow start,
because service dependecy was missing at all. Committed patch, accidentally in master branch, sry for that. eccedbec5603e7f556e2dd3ac0d9ad5c2998c833

**Closed** 2018-10-09 23:07 UTC
Labels: bug, detector
